"use client";

export default function PostCard() {
  return (
    <div className="post_container">
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
      <div>게시글</div>
    </div>
  );
}
